### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ticalc-travis** [Legend-of-iPhoenix/TheButton#33]
It would be a good idea to [select a license](https://help.github.com/articles/licensing-a-repository/) for this project so that it is clear to all what the terms are for using and contributing to the code. In the absence of a clear license, copyright laws in most jurisdictions prohibit copying or modification without permission (which would include forking and contributing on GitHub).

**Comment by josheewa** [comment]
If I use Adriweb's button code, I think it'd have to be GPL. (according to adriweb)

**Comment by adriweb** [comment]
True although my dark mode button code is probably so tiny it could be something you could have come up with yourself :P
That said tev is right about choosing a license. GPL is nice to « protect » open source code from abuse, let’s say. But for things like libraries (not our case here), it’s  annoying since anything that uses it must be GPL too.

**Comment by Legend-of-iPhoenix** [comment]
I'm rejecting the pull request anyways because we could easily do something better, and the code he (@jcgter777) tried to add wouldn't do what he thinks it does.

I selected the GPL license, though.
